using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Mongo.Models
{
    public class ProfissaoModel
    {
        public int group { get; set; }
        public string name { get; set; }

        public List<ProfissaoModel> ListaProfissoes()
        {
            return new List<ProfissaoModel>
            {
                new ProfissaoModel{ group =  1,  name = "Administração"},
                new ProfissaoModel{ group =  1,  name = "Administração Pública"},
                new ProfissaoModel{ group =  1,  name = "Agronegócios e Agropecuária"},
                new ProfissaoModel{ group =  1,  name = "Ciências Aeronáuticas"},
                new ProfissaoModel{ group =  1,  name = "Ciências Atuariais"},
                new ProfissaoModel{ group =  1,  name = "Ciências Contábeis"},
                new ProfissaoModel{ group =  1,  name = "Ciências Econômicas"},
                new ProfissaoModel{ group =  1,  name = "Comércio Exterior"},
                new ProfissaoModel{ group =  1,  name = "Defesa e Gestão Estratégica Internacional"},
                new ProfissaoModel{ group =  1,  name = "Empresário"},
                new ProfissaoModel{ group =  1,  name = "Empreendedor"},
                new ProfissaoModel{ group =  1,  name = "Gastronomia"},
                new ProfissaoModel{ group =  1,  name = "Gestão Comercial"},
                new ProfissaoModel{ group =  1,  name = "Gestão de Recursos Humanos"},
                new ProfissaoModel{ group =  1,  name = "Gestão de Segurança Privada"},
                new ProfissaoModel{ group =  1,  name = "Gestão de Seguros"},
                new ProfissaoModel{ group =  1,  name = "Gestão de Turismo"},
                new ProfissaoModel{ group =  1,  name = "Gestão Financeira"},
                new ProfissaoModel{ group =  1,  name = "Gestão Pública"},
                new ProfissaoModel{ group =  1,  name = "Hotelaria"},
                new ProfissaoModel{ group =  1,  name = "Logística"},
                new ProfissaoModel{ group =  1,  name = "Marketing"},
                new ProfissaoModel{ group =  1,  name = "Negócios Imobiliários"},
                new ProfissaoModel{ group =  1,  name = "Pilotagem profissional de aeronaves"},
                new ProfissaoModel{ group =  1,  name = "Processos Gerenciais"},
                new ProfissaoModel{ group =  1,  name = "Segurança Pública"},
                new ProfissaoModel{ group =  1,  name = "Turismo"},


                new ProfissaoModel{ group =  2,  name = "Animação"},
                new ProfissaoModel{ group =  2,  name = "Arquitetura e Urbanismo"},
                new ProfissaoModel{ group =  2,  name = "Artes Visuais"},
                new ProfissaoModel{ group =  2,  name = "Comunicação das Artes do Corpo"},
                new ProfissaoModel{ group =  2,  name = "Conservação e Restauro"},
                new ProfissaoModel{ group =  2,  name = "Dança"},
                new ProfissaoModel{ group =  2,  name = "Design"},
                new ProfissaoModel{ group =  2,  name = "Design de Games"},
                new ProfissaoModel{ group =  2,  name = "Design de Interiores"},
                new ProfissaoModel{ group =  2,  name = "Design de Moda"},
                new ProfissaoModel{ group =  2,  name = "Fotografia"},
                new ProfissaoModel{ group =  2,  name = "História da Arte"},
                new ProfissaoModel{ group =  2,  name = "Jogos Digitais"},
                new ProfissaoModel{ group =  2,  name = "Luteria"},
                new ProfissaoModel{ group =  2,  name = "Música"},
                new ProfissaoModel{ group =  2,  name = "Produção Cênica"},
                new ProfissaoModel{ group =  2,  name = "Produção Fonográfica"},
                new ProfissaoModel{ group =  2,  name = "Teatro"},


                new ProfissaoModel{ group =  3,  name = "Agroecologia"},
                new ProfissaoModel{ group =  3,  name = "Agronomia"},
                new ProfissaoModel{ group =  3,  name = "Alimentos"},
                new ProfissaoModel{ group =  3,  name = "Biocombustíveis"},
                new ProfissaoModel{ group =  3,  name = "Biotecnologia"},
                new ProfissaoModel{ group =  3,  name = "Biotecnologia e Bioquímica"},
                new ProfissaoModel{ group =  3,  name = "Ciência e Tecnologia de Alimentos"},
                new ProfissaoModel{ group =  3,  name = "Ciências Agrárias"},
                new ProfissaoModel{ group =  3,  name = "Ciências Biológicas"},
                new ProfissaoModel{ group =  3,  name = "Ciências Naturais e Exatas"},
                new ProfissaoModel{ group =  3,  name = "Ecologia"},
                new ProfissaoModel{ group =  3,  name = "Geofísica"},
                new ProfissaoModel{ group =  3,  name = "Geologia"},
                new ProfissaoModel{ group =  3,  name = "Gestão Ambiental"},
                new ProfissaoModel{ group =  3,  name = "Medicina Veterinária"},
                new ProfissaoModel{ group =  3,  name = "Meteorologia"},
                new ProfissaoModel{ group =  3,  name = "Oceanografia"},
                new ProfissaoModel{ group =  3,  name = "Produção de Bebidas"},
                new ProfissaoModel{ group =  3,  name = "Produção Sucroalcooleira"},
                new ProfissaoModel{ group =  3,  name = "Rochas Ornamentais"},
                new ProfissaoModel{ group =  3,  name = "Zootecnia"},


                new ProfissaoModel{ group =  4,  name = "Astronomia"},
                new ProfissaoModel{ group =  4,  name = "Banco de Dados"},
                new ProfissaoModel{ group =  4,  name = "Ciência da Computação"},
                new ProfissaoModel{ group =  4,  name = "Ciência e Tecnologia"},
                new ProfissaoModel{ group =  4,  name = "Computação"},
                new ProfissaoModel{ group =  4,  name = "Informática"},
                new ProfissaoModel{ group =  4,  name = "Estatística"},
                new ProfissaoModel{ group =  4,  name = "Física"},
                new ProfissaoModel{ group =  4,  name = "Gestão da Tecnologia da Informação"},
                new ProfissaoModel{ group =  4,  name = "Informática Biomédica"},
                new ProfissaoModel{ group =  4,  name = "Matemática"},
                new ProfissaoModel{ group =  4,  name = "Nanotecnologia"},
                new ProfissaoModel{ group =  4,  name = "Química"},
                new ProfissaoModel{ group =  4,  name = "Redes de Computadores"},
                new ProfissaoModel{ group =  4,  name = "Segurança da Informação"},
                new ProfissaoModel{ group =  4,  name = "Sistemas de Informação"},
                new ProfissaoModel{ group =  4,  name = "Sistemas para Internet"},


                new ProfissaoModel{ group =  5,  name = "Arqueologia"},
                new ProfissaoModel{ group =  5,  name = "Ciências do Consumo"},
                new ProfissaoModel{ group =  5,  name = "Ciências Humanas"},
                new ProfissaoModel{ group =  5,  name = "Ciências Sociais"},
                new ProfissaoModel{ group =  5,  name = "Cooperativismo"},
                new ProfissaoModel{ group =  5,  name = "Direito"},
                new ProfissaoModel{ group =  5,  name = "Escrita Criativa"},
                new ProfissaoModel{ group =  5,  name = "Estudos de Gênero e Diversidade"},
                new ProfissaoModel{ group =  5,  name = "Filosofia"},
                new ProfissaoModel{ group =  5,  name = "Geografia"},
                new ProfissaoModel{ group =  5,  name = "Gestão de Cooperativas"},
                new ProfissaoModel{ group =  5,  name = "História"},
                new ProfissaoModel{ group =  5,  name = "Letras"},
                new ProfissaoModel{ group =  5,  name = "Libras"},
                new ProfissaoModel{ group =  5,  name = "Linguística"},
                new ProfissaoModel{ group =  5,  name = "Museologia"},
                new ProfissaoModel{ group =  5,  name = "Pedagogia"},
                new ProfissaoModel{ group =  5,  name = "Psicopedagogia"},
                new ProfissaoModel{ group =  5,  name = "Relações Internacionais"},
                new ProfissaoModel{ group =  5,  name = "Serviço Social"},
                new ProfissaoModel{ group =  5,  name = "Serviços Judiciários e Notariais"},
                new ProfissaoModel{ group =  5,  name = "Teologia"},
                new ProfissaoModel{ group =  5,  name = "Tradutor e Intérprete"},


                new ProfissaoModel{ group =  6,  name = "Arquivologia"},
                new ProfissaoModel{ group =  6,  name = "Biblioteconomia"},
                new ProfissaoModel{ group =  6,  name = "Cinema e Audiovisual"},
                new ProfissaoModel{ group =  6,  name = "Comunicação em Mídias Digitais"},
                new ProfissaoModel{ group =  6,  name = "Comunicação Institucional"},
                new ProfissaoModel{ group =  6,  name = "Comunicação Organizacional"},
                new ProfissaoModel{ group =  6,  name = "Educomunicação"},
                new ProfissaoModel{ group =  6,  name = "Estudos de Mídia"},
                new ProfissaoModel{ group =  6,  name = "Eventos"},
                new ProfissaoModel{ group =  6,  name = "Gestão da Informação"},
                new ProfissaoModel{ group =  6,  name = "Jornalismo"},
                new ProfissaoModel{ group =  6,  name = "Produção Audiovisual"},
                new ProfissaoModel{ group =  6,  name = "Produção Cultural"},
                new ProfissaoModel{ group =  6,  name = "Produção Editorial"},
                new ProfissaoModel{ group =  6,  name = "Produção Multimídia"},
                new ProfissaoModel{ group =  6,  name = "Produção Publicitária"},
                new ProfissaoModel{ group =  6,  name = "Publicidade e Propaganda"},
                new ProfissaoModel{ group =  6,  name = "Rádio, TV e Internet"},
                new ProfissaoModel{ group =  6,  name = "Relações Públicas"},
                new ProfissaoModel{ group =  6,  name = "Secretariado"},
                new ProfissaoModel{ group =  6,  name = "Secretariado Executivo"},


                new ProfissaoModel{ group =  7,  name = "Agrimensura"},
                new ProfissaoModel{ group =  7,  name = "Aquicultura"},
                new ProfissaoModel{ group =  7,  name = "Automação Industrial"},
                new ProfissaoModel{ group =  7,  name = "Construção Civil"},
                new ProfissaoModel{ group =  7,  name = "Construção Naval"},
                new ProfissaoModel{ group =  7,  name = "Eletrônica Industrial"},
                new ProfissaoModel{ group =  7,  name = "Eletrotécnica Industrial"},
                new ProfissaoModel{ group =  7,  name = "Energias Renováveis"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Acústica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Aeronáutica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Agrícola"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Ambiental e Sanitária"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Biomédica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Bioquímica, de Bioprocessos e Biotecnologia"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Cartográfica e de Agrimensura"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Civil"},
                new ProfissaoModel{ group =  7,  name = "Engenharia da Computação"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Alimentos"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Biossistemas"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Controle e Automação"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Energia"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Inovação"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Materiais"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Minas"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Pesca"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Petróleo"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Produção"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Segurança no Trabalho"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Sistemas"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Software"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Telecomunicações"},
                new ProfissaoModel{ group =  7,  name = "Engenharia de Transporte e da Mobilidade"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Elétrica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Eletrônica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Física"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Florestal"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Hídrica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Industrial Madeireira"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Mecânica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Mecatrônica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Metalúrgica"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Naval"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Nuclear"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Química"},
                new ProfissaoModel{ group =  7,  name = "Engenharia Têxtil"},
                new ProfissaoModel{ group =  7,  name = "Fabricação Mecânica"},
                new ProfissaoModel{ group =  7,  name = "Geoprocessamento"},
                new ProfissaoModel{ group =  7,  name = "Gestão da Produção Industrial"},
                new ProfissaoModel{ group =  7,  name = "Gestão da Qualidade"},
                new ProfissaoModel{ group =  7,  name = "Irrigação e Drenagem"},
                new ProfissaoModel{ group =  7,  name = "Manutenção de aeronaves"},
                new ProfissaoModel{ group =  7,  name = "Manutenção Industrial"},
                new ProfissaoModel{ group =  7,  name = "Materiais"},
                new ProfissaoModel{ group =  7,  name = "Mecatrônica Industrial"},
                new ProfissaoModel{ group =  7,  name = "Mineração"},
                new ProfissaoModel{ group =  7,  name = "Papel e Celulose"},
                new ProfissaoModel{ group =  7,  name = "Petróleo e Gás"},
                new ProfissaoModel{ group =  7,  name = "Processos Metalúrgicos"},
                new ProfissaoModel{ group =  7,  name = "Processos Químicos"},
                new ProfissaoModel{ group =  7,  name = "Produção Têxtil"},
                new ProfissaoModel{ group =  7,  name = "Saneamento Ambiental"},
                new ProfissaoModel{ group =  7,  name = "Segurança no Trabalho"},
                new ProfissaoModel{ group =  7,  name = "Silvicultura"},
                new ProfissaoModel{ group =  7,  name = "Sistemas Biomédicos"},
                new ProfissaoModel{ group =  7,  name = "Sistemas de Telecomunicações"},
                new ProfissaoModel{ group =  7,  name = "Sistemas Elétricos"},
                new ProfissaoModel{ group =  7,  name = "Sistemas Embarcados"},
                new ProfissaoModel{ group =  7,  name = "Transporte"},


                new ProfissaoModel{ group =  8,  name = "Biomedicina"},
                new ProfissaoModel{ group =  8,  name = "Educação Física"},
                new ProfissaoModel{ group =  8,  name = "Enfermagem"},
                new ProfissaoModel{ group =  8,  name = "Esporte"},
                new ProfissaoModel{ group =  8,  name = "Estética e Cosmética"},
                new ProfissaoModel{ group =  8,  name = "Farmácia"},
                new ProfissaoModel{ group =  8,  name = "Fisioterapia"},
                new ProfissaoModel{ group =  8,  name = "Fonoaudiologia"},
                new ProfissaoModel{ group =  8,  name = "Gerontologia"},
                new ProfissaoModel{ group =  8,  name = "Gestão Desportiva e de Lazer"},
                new ProfissaoModel{ group =  8,  name = "Gestão em Saúde"},
                new ProfissaoModel{ group =  8,  name = "Gestão Hospitalar"},
                new ProfissaoModel{ group =  8,  name = "Medicina"},
                new ProfissaoModel{ group =  8,  name = "Musicoterapia"},
                new ProfissaoModel{ group =  8,  name = "Naturologia"},
                new ProfissaoModel{ group =  8,  name = "Nutrição"},
                new ProfissaoModel{ group =  8,  name = "Obstetrícia"},
                new ProfissaoModel{ group =  8,  name = "Odontologia"},
                new ProfissaoModel{ group =  8,  name = "Oftálmica"},
                new ProfissaoModel{ group =  8,  name = "Optometria"},
                new ProfissaoModel{ group =  8,  name = "Psicologia"},
                new ProfissaoModel{ group =  8,  name = "Quiropraxia"},
                new ProfissaoModel{ group =  8,  name = "Radiologia"},
                new ProfissaoModel{ group =  8,  name = "Saúde Coletiva"},
                new ProfissaoModel{ group =  8,  name = "Terapia Ocupacional"},
            };
        }
    }
}
